Added project to list
mictab/g5-projects pull request #1
Opened 2017-04-10 10:04 UTC by worldyn

Adam Jacobs and Olle Berglöf's project description. Will add github account name soon.

2017-04-10 11:29 UTC, mictab requested changes

2017-04-10 11:29 UTC, mictab commented on README.md
> +HOUSEFINDER - A SaaS that will help you easily look for an apartment/house rental contract via a web crawler that collects the latest info from several websites with rental contracts. Created by Adam
Could you make HOUSEFINDER into a link maybe? Like so.

```
[HOUSEFINDER](https://github.com/worldyn/house-web-crawler)
```

And the same for the Github usernames.

Will approve and merge when your partner is listed as well 👍

2017-04-11 10:20 UTC, worldyn commented
@mictab added link to repository and accounts :)

2017-04-12 19:31 UTC, mictab approved these changes

2017-04-12 19:31 UTC, merged